data:
  # json, mongodb
  store: "mongodb"

  # Smart caching mode (แนะนำสำหรับ 2000 คน)
  smart-caching: true

  # Cache จะ refresh ทุก 30 วินาที
  cache-refresh-seconds: 30

  # Cache จะถูกลบออกถ้าไม่ได้ใช้เกิน 10 นาที
  cache-ttl-minutes: 10

  # บันทึกอัตโนมัติเมื่อมีการอัพเดท (ปิดเพื่อลด database load)
  auto-save-on-update: false

  mongodb:
    uri: "mongodb://localhost:27017"
    database: "hmcrewards"

# การตั้งค่า MongoDB Connection Pool
mongodb:
  connection-pool:
    max-pool-size: 50          # เพียงพอสำหรับ 2000 คน
    min-pool-size: 5           # รักษา connection พื้นฐาน
    max-wait-time-ms: 10000    # รอ connection สูงสุด 10 วินาที
    max-connection-idle-time-ms: 300000  # 5 นาที
    max-connection-life-time-ms: 1800000 # 30 นาที

toasts:
  enabled: true

# configure the used sounds, the format is:
#    <type> [volume] [pitch]
# the type must be Minecraft's sound name, check
# a full list here: https://www.digminecraft.com/lists/sound_list_pc.php
# Also note that sounds are optional, you can just remove
# one and it will not play
sounds:
  # reward-give: 'entity.player.levelup 1 1'
  # reward-give-error: 'entity.villager.no 1 1'
  # reward-bulk-claim: 'entity.player.levelup 1 1'
  # reward-bulk-claim-error: 'entity.villager.no 1 1'

rewards:
  example_command:
    type: "command"

    # Required Inventory Slots for claiming
    required-space: dynamic

    # icon
    display:
      material: 'PAPER'
      custom-model-data: 3
      name: '<red>Example Command Reward'
      lore:
        - '<#d24c9f><bold>Contains:'
        - '<dark_gray>x1 <aqua>Diamond'
        - '<dark_gray>x1 <gold>Enchanted Golden Apple'
        - '<dark_gray>x1 <green>Emerald'

    # Commands to deliver to player
    commands:
      - 'say %player% claimed a command reward from HMCRewards!'
      - 'minecraft:give %player% minecraft:diamond'
      - 'minecraft:give %player% minecraft:enchanted_golden_apple 1'
      - 'minecraft:give %player% minecraft:emerald 1'



  example_dynamic_reward:
    type: dynamic
    display:
      material: 'CHEST'
      custom-model-data: 1
      name: '<green>Dynamic Reward Example'
      lore:
        - 'A dynamic reward!'
        - 'Configured with arguments!'
    arguments:
      arg_1:
        value: 64        # Default value for arg_1
        stackable: true
        stack-size: 64   # Max stack size
      arg_2:
        value: 32        # Default value for arg_2
        stackable: false # Cannot stack in inventory
    commands:
      - 'say %player% received %arg_1% diamonds and %arg_2% netherite ingots!'
      - 'minecraft:give %player% minecraft:diamond %arg_1%'
      - 'minecraft:give %player% minecraft:netherite_ingot %arg_2%'